#apiVersion: operators.coreos.com/v1alpha1
#kind: Subscription
#metadata:
#  name: {{ .Values.subscriptions.ibmautomation.name }}
#  namespace: {{ .Values.subscriptions.ibmautomation.namespace }}
#  annotations:
#spec:
#  {{- toYaml .Values.subscriptions.ibmautomation.subscription | nindent 2 }}


apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cp4a-operator
  #namespace: {{ .Values.subscriptions.ibmautomation.namespace }}
  namespace: {{ .Values.cp4ba.namespace }}
  #namespace: gitops-cp-cp4ba-operator
spec:
  channel: {{ .Values.cp4ba.channel }}
  installPlanApproval: Automatic
  name: ibm-cp4a-operator
  source: {{ .Values.cp4ba.source }}
  sourceNamespace: {{ .Values.cp4ba.sourcenamespace }}
